title: "Devesh Pawar"
email: contact@devesh.design
description: >- # this means to ignore newlines until "baseurl:"
 I'm a Full-stack Web developer and product designer based in Mumbai, India. I enjoy turning complex problems into simple, 
 beautiful and intuitive designs. When I'm not coding, pushing pixels, you'll find me playing games, 
 binge-watching or going out with my friends.
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: dev_2919
github_username:  dev2919

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg